<?php

$labels = array(
    "normalmode.text" => 'MESSAGE LIST', 
    "messagemode.text" => "MESSAGE", 
    "followliksmode.text" => "FOLLOW LINKS", 
    "messagecaretmode.text" => 'CARET', 
    "visualmode.text" => "VISUAL",
    "foldersmode.text" => "FOLDERS SELECT", 
    "composemode.txt" => "COMPOSE", 
    "insertmode.txt" => "INSERT", 
    "attdeletemode.txt" => "ATTACHMENTS DELETE", 
    'contactsmode.txt' => "CONTACTS SEARCH",
    "search.result" => "#idx# of #count# result#s# found.",
    "search.noresult" => "No results found", 
    "disabled" => "MUTTCUBE currently disabled", 
);
?>
